### PR TITLE
Image shows on profile pic with hardcoded bytes.

### PR DESCRIPTION
**Pull request by VillanuevaK**
Only changed profile.jsp, but maven updated. Not sure how to handle this. The hard coded image on the jsp file shows now though.

### CODE REVIEW

**Review by yufangqq — COMMENTED** [review]
Hi Kevin, this is hard to review, so many files are marked changed (even though their content might not have changed).

Can you start a clean new branch, 'sync''ed to 'master, and make sure you ONLY create the changes necessary for the "profile pic" in this new branch, and submit a fresh pull request, let's see if that way, we can limit the "pull request" to ONLY files you changed?

**Comment by VillanuevaK** [comment]
Alright, I'll get on that. What should I do with the rest of the changes on
the code?

**Comment by yufangqq** [comment]
What do you mean "rest of the changes"?

**Comment by VillanuevaK** [comment]
The unintended changes from updating maven. Do I just ignore them?

**Comment by yufangqq** [comment]
Just focus on the 'pull request' for the profile pic feature. A 'pull request' should be a single change. Let's treat that 'maven update' as a separate thing.

**Comment by yufangqq** [comment]
Do you know why you are getting those " unintended changes from updating maven"? Did you run some command to update maven? If it is due to some update you did, what you should do is that treat that as a separate pull request, e.g., pull request with description "Maven updates".

**Comment by VillanuevaK** [comment]
I did the standard mvn appengine:devserver to see my changes on the local
host, and it started updating automatically. At least I assume it was an
update.

**Comment by yufangqq** [comment]
Oh, I see. Interesting. I guess in your fresh new branch. WIHTOUT any local changes, do a mvn appengine:devserver. If you got the same file updates, then you do a "Maven updates" pull request first. Then after that is all updated, we do a "Profile pic" pull request.

**Comment by VillanuevaK** [comment]
Hmm. Will do. I'll just delete this branch.

**Comment by yufangqq** [comment]
Just make sure you have backed up (copy the files to somewhere else) your local work before you delete any branch.

**Pull request closed without merging**
